### ISSUE TITLE
typo: "perforated" mistakenly typed as "perferated"

### ISSUE THREAD

**Issue by Meknassih** [twbs/icons#1118] opened 2021-12-02 19:03 UTC
Not really a bug, but I noticed these two icons names have a typo: 
- ticket-perferated
- ticket-perferated-fill

It should be : 
- ticket-perforated
- ticket-perforated-fill

**Comment by mdo** [comment] 2021-12-02 20:09
Duplicate of #1102.

**Closed by mdo** 2021-12-02 20:09 UTC
Labels: bug
