### ISSUE TITLE
SVG Icon `path`s are hard to manually adjust

### ISSUE THREAD

**Issue by ex-tag** [twbs/icons#1443] opened 2022-09-25 19:44 UTC
SVG icon paths are hard to manually adjust

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
  fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">

  <!-- 😭 -->
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
</svg>
```
---

1. Line commands should have spaces, so they are readable
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#line_commands
`M 11.742` not `M11.742`

2. Use spaces between numbers
`c.03.04.062.078.098.115` ...how do I read that number?

3. Keep 3 significant values on all numbers.  
`M11.742 10.344a6.500 0.000 1.000` not `M11.742 10.344a6.500 0 1`  
Also makes it easier to adjust numbers up and down  
`M11.742 10.344a6.500 0.000` => `M11.742 10.344a6.500 0.001`

4. Use newline on Line Commands, to keep to 80 characters per line

---

Before:
```svg
<!-- 😭 -->
<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
```

After:
```svg
<!-- 🙂 -->
<path d="
  M 11.742 10.344
  a 6.500 6.500 0.000 1.000 0.000 -1.397 1.398
  h -0.001
  c 0.030 0.040 0.062 0.078 0.098 0.115
  l 3.850 3.850
  a 1.000 1.000 0.000 0.000 0.000 1.415 -1.414
  l -3.850 -3.850
  a 1.007 1.007 0.000 0.000 0.000 -0.115 -0.100
  z
  M 12.000 6.500
  a 5.500 5.500 0.000 1.000 1.000 -11.000 0.000
    6.500 5.500 0.000 0.000 1.000 11.000 0.000
  z
"/>
```

**Comment by mdo** [comment] 2022-10-29 18:30
Closing this as not a bug—we compress and optimize the SVGs programmatically, so we there's not much sense from our perspective to manually tweak the path definitions for ~2000 icons :).

**Closed by mdo** 2022-10-29 18:30 UTC
Labels: bug
