### ISSUE TITLE
Web/digital accessibility icon

### ISSUE THREAD

**Issue by michielduijsings** [twbs/icons#1237] opened 2022-02-23 15:05 UTC
Hi, an icon for web/digital accessibility would be very nice,  Like this one:

![image](https://user-images.githubusercontent.com/45594381/155346268-a1408281-bfb5-476c-baef-6cbd598c474f.png)

**Comment by mdo** [comment] 2022-07-08 23:24
Duplicate of #498.

**Closed by mdo** 2022-07-08 23:24 UTC
Labels: icon-request
