### ISSUE TITLE
Icon vertical alignment still a problem

### ISSUE THREAD

**Issue by blackblather** [twbs/icons#921] opened 2021-06-20 08:27 UTC
Hey everyone.

I downloaded the bootstrap 5 css/js files from this [download page](https://getbootstrap.com/docs/5.0/getting-started/download/) and the svg icons in the buttons are still misaligned.
Then tried to import directly as shown in this [introduction page](https://getbootstrap.com/docs/5.0/getting-started/introduction/) and is also misaligned.

After looking a bit, found this issue #82 and this pull request #701.

It seems the changes have been merged to `main` but not made available to download yet on the website.
Also, the [header example](https://getbootstrap.com/docs/5.0/examples/headers/) seems to be using an older version of the `bootstrap.css` because in the `headers.css` it is using:
```
.bi {
  vertical-align: -.125em;
  fill: currentColor;
}
```
to fix this issue instead of it being directly in the `bootstrap.css` file.

Is this expected?

**Comment by mdo** [comment] 2022-07-16 20:30
Duplicate of #913.

**Closed by mdo** 2022-07-16 20:30 UTC
Labels: bug
