### ISSUE TITLE
<i class="bi bi-bag"></i> is not looking same as shown 

### ISSUE THREAD

**Issue by Lekhrajk** [twbs/icons#548] opened 2020-12-14 07:22 UTC
- Operating system and version (Windows)
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)

I tested in many different browsers but the icon is looking very different
<img width="37" alt="issue-bag-icon" src="https://user-images.githubusercontent.com/42565741/102051856-359d5d80-3e0b-11eb-88bf-f9c80297c718.png">

**Comment by ffes** [comment] 2020-12-14 09:47
I opened `font/index.html` from `bootstrap-icons-1.2.1.zip` and **many** icons don't look as expected.

Just two little examples:
![afbeelding](https://user-images.githubusercontent.com/3225656/102065818-53fa5d80-3df9-11eb-9ee4-1b111d801ecb.png)
![afbeelding](https://user-images.githubusercontent.com/3225656/102066112-b7848b00-3df9-11eb-9b1f-664192e17c50.png)

**Comment by mdo** [comment] 2020-12-14 17:33
Duplicate of #545.

**Closed by mdo** 2020-12-14 17:33 UTC
Labels: bug
