### ISSUE TITLE
[Icon request] Telephone receiver

### ISSUE THREAD

**Issue by MrKuzio** [twbs/icons#289] opened 2020-06-05 04:04 UTC
It would be great if we could have the telephone receiver icon, something like this: https://emojipedia.org/telephone-receiver/

**Comment by mdo** [comment] 2020-06-05 05:11
Duplicate of #211 and #265. Coming in the next release!

**Closed by mdo** 2020-06-05 05:11 UTC

**Comment by DimIsaev** [comment] 2020-06-25 03:47
wait  this icons. thanks
