### ISSUE TITLE
Website search for `plus-square` does not yield a result

### ISSUE THREAD

**Issue by davidsneighbour** [twbs/icons#1498] opened 2022-11-17 14:19 UTC
Sorry, if this is not understood as a bug. It's at least a nuisance :)

Going to https://icons.getbootstrap.com/ and then searching for `plus-square` in the icon search field does not yield a result. I would expect the bi-plus-square icon to come up (at least). 

`plus` alone brings up all the plusses, but as soon as I type the dash the search results stay empty. search for `plus square` shows `plus-square`.

Could this be an issue with dash/minus in the search functionality?

**Comment by XhmikosR** [comment] 2023-03-24 22:38
Duplicate of #895

**Closed by XhmikosR** 2023-03-24 22:38 UTC
Labels: bug, docs
