### ISSUE TITLE
LinkedIn Icon issue: Font files included through Webpack

### ISSUE THREAD

**Issue by adityakahb** [twbs/icons#562] opened 2020-12-19 18:16 UTC
Hi, I included the node package in the project and then compiled the CSS and fonts through Webpack file-loader. So far, I could see that the LinkedIn icon is broken when used as `<i class="bi bi-linkedin"></i>`.

Please refer to the screenshot.

![linkedin-icon](https://user-images.githubusercontent.com/8940209/102696330-8ff74d80-4253-11eb-962f-bc295e4361df.png)

- Operating system: Windows 10 Home 20H2
- Browsers and versions: All latest browsers including IE11

**Comment by mdo** [comment] 2020-12-19 18:20
Duplicate of #545

**Closed by mdo** 2020-12-19 18:20 UTC
Labels: bug
