### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by petervannes** [twbs/icons#1513] opened 2022-11-25 13:43 UTC
Broken link icon, based on https://icons.getbootstrap.com/icons/link/

**Comment by ddudda174** [comment] 2023-06-14 14:46
Would also like to see different version. Not just the strikethrough one, but maybe a "broken" chain also?

I also required this and fiddled a bit with the existing svg paths. Feel free to use it until we get an "official" version 🙂 

![image](https://github.com/twbs/icons/assets/67892761/44b28eee-69dc-4c22-bf44-faa1913190aa)

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-unlink" viewBox="0 0 16 16">
    <path d="M4 5.5H4a3 3 0 000 6h3A3 3 0 009.009 10.753L8.253 9.989A2 2 0 017 10.5H4a2 2 0 110-4h.889zM9 5.5a3 3 0 00-1.993.78l.727.733A2 2 0 019 6.5h3a2 2 0 110 4h-.777l1.002 1.002a2 2 0 10-.226-5.998H9.001zM7.001 8.508 6.131 7.618A1.25 2 0 006.169 9.503H7.269A1 1.5 0 017.006 8.508zM1.65 2.35a.5.5 0 01.708-.708l12 12a.5.5 0 01-.708.708l-12-12"></path>
</svg>
```

**Comment by mdo** [comment] 2023-06-14 21:24
Duplicate of #436.

**Closed by mdo** 2023-06-14 21:24 UTC
Labels: icon-request
