### ISSUE TITLE
Wrong size or viewport?

### ISSUE THREAD

**Issue by Seswu** [twbs/icons#203] opened 2020-04-04 06:51 UTC
In filemanager (thunar, linux) and in PyQt5 (QIcon) the icons are all jumbled up when loaded. Unrecognizable.
Somehow they fail to display the way they should.
Other svg icon packs display correctly following same procedures.

**Comment by mdo** [comment] 2020-04-08 17:40
This was likely a duplicate of #210 which was fixed with #213. I expect this to work with our Alpha 4 release.

**Closed by mdo** 2020-04-08 17:40 UTC
