### ISSUE TITLE
How to check unicode for certain icons?

### ISSUE THREAD

**Issue by chrisooo3** [twbs/icons#979] opened 2021-08-13 07:36 UTC
I need to display icons in select input in `<option />` tag,
How to check unicode of your's icons? 
I need to know what are the unicodes for these icons:
1. `<i class="bi bi-sort-alpha-up"></i>`
2. `<i class="bi bi-sort-alpha-down"></i>`

Thanks in advance!

**Comment by RubenVerg** [comment] 2021-08-13 07:51
if I remember correctly there's a PR for showing them in the icon page, for now I think you have to open the css file and search for the icon manually

**Comment by mdo** [comment] 2022-01-29 00:04
Duplicate of #891.

**Closed by mdo** 2022-01-29 00:04 UTC
Labels: docs, enhancement
