### ISSUE TITLE
f(x) Function Icon

### ISSUE THREAD

**Issue by savejeff** [twbs/icons#1573] opened 2023-01-25 12:31 UTC
I would like to request an "f(x)" Icon
I think the text alone would be enough.
Other Math Related would also be cool like integral or differential

thanks

**Comment by korki43** [comment] 2023-03-27 19:35
Related to #1268.

**Comment by mdo** [comment] 2023-04-03 01:11
Duplicate of #1079.

**Closed by mdo** 2023-04-03 01:11 UTC
Labels: icon-request
