### ISSUE TITLE
Social Media Icons 

### ISSUE THREAD

**Issue by dh00mk3tu** [twbs/icons#380] opened 2020-07-30 05:28 UTC
There's no support for social media icons.
Major one's that really should be included 

1. Quora
2. Twitter
3. Telegram
4. Facebook
5. YouTube
6. Instagram
7. WhatsApp
8. Twitch 
9. GitHub  
10. Outlook
11. LinkedIn

**Comment by mdo** [comment] 2020-07-30 06:56
Duplicate of #96.

**Closed by mdo** 2020-07-30 06:56 UTC
Labels: icon-request

**Comment by dh00mk3tu** [comment] 2020-07-30 06:58
Oh,
I am sorry, I did check in on previous issues but didn't find this one in particular
