### ISSUE TITLE
[Icon font] Some Icon contents fully filled with the font color

### ISSUE THREAD

**Issue by chindil** [twbs/icons#545] opened 2020-12-13 10:52 UTC
Some icons (some of them are listed below) showing fully filled with the font color, the content is not visible.  Refer to the attached image. 

Eg: arrow-down-circle is displaying as fully colored black circle (font color is black; same for any color), no down-arrow is visible. tested with 3 different browsers.  

version: v1.2.1
![image](https://user-images.githubusercontent.com/39211754/102009713-49e24b80-3d74-11eb-8520-bb5ce5615caf.png)

**Comment by chuckych** [comment] 2020-12-13 14:19
I have the same problem. Some icon fonts d'ont work.

**Comment by mdo** [comment] 2020-12-13 20:24
Thanks for testing, and sorry for the snags! I'll take a look soon!

**Comment by mdo** [comment] 2020-12-13 22:29
Hmm, what browsers and version? Latest Chrome, Safari, and Firefox on macOS looks great overall. Seeing a couple problems, but nothing like the above screenshot.

**Comment by mikouaji** [comment] 2020-12-13 22:45
I have the same problem, if I remember correctly last time when I had similar problem with some icon font I used this to modify the font file somehow https://fontforge.org/en-US/
Chrome Version 87.0.4280.88
Firefox 83.0
Linux Mint 19.3

**Comment by chindil** [comment] 2020-12-14 06:39
I have tested this with both Microsoft Edge Version 87.0.664.60 & Google Chrome Version 87.0.4280.88. 
Not sure this is due to an issue with the font or due to my system issue. 
however i saw some strange things in some chars as showing in the below image.. pls consider it, if it makes any sense.. .
![image](https://user-images.githubusercontent.com/39211754/102048355-f62a3d80-3e19-11eb-9681-a1e259bc1d9d.png)

**Comment by ffes** [comment] 2020-12-14 19:25
As I wrote in #548, this is an easy way to reproduce the problem

> I opened font/index.html from bootstrap-icons-1.2.1.zip and many icons don't look as expected.

**Comment by bas-surlinio** [comment] 2020-12-14 21:19
Same problem here with the phone and tablet icons on both chrome (Version 87.0.4280.88 (Official Build) (x86_64)) and Safari (14.0.1 (16610.2.11.51.8) on MacOs Big Sur 11.0.1

**Comment by mdo** [comment] 2020-12-15 05:22
Looks like I can resolve most of this by playing with the SVG `fill-rule` settings with a Figma plugin. Will take a little time to get all these icons done right again, sorry y'all.

**Comment by singhprem166** [comment] 2020-12-18 07:21
I have the same problem 

`<i class="bi bi-geo-alt-fill"></i>`


![svg_icon_problem](https://user-images.githubusercontent.com/61229245/102586139-97bdd180-412f-11eb-89a4-dc6de2663be5.PNG)

**Comment by Prazdnik** [comment] 2020-12-21 10:39
@mdo Hello, can you tell me how long it will take to solve this problem? Thank you in advance.

**Comment by mdo** [comment] 2020-12-21 17:39
I have to redraw and re-export nearly every icon, so it's taking some time. 😬 I don't have an ETA right now.

**Comment by mdo** [comment] 2020-12-22 00:42
You can follow along in #552 btw. Pushing updated icons bit by bit.

**Comment by mdo** [comment] 2020-12-22 04:06
Nearly done with the update in #552. Still have a chunk of icons to fix up and review, but I'm nearly there. Will do a point release as soon as I can afterwards to get it shipped.

**Comment by muthuweb** [comment] 2020-12-22 13:16
@mdo 
This may happening while converting svg to fonts,
Few months ago, I faced the same with gulp-icon, then I tried with http://icomoon.io website to convert myself, then it's almost fine.

**Comment by mdo** [comment] 2020-12-22 23:28
Fixed by #552.

**Closed by mdo** 2020-12-22 23:28 UTC
Labels: bug

**Comment by singhprem166** [comment] 2020-12-24 11:28
❤👍
