### ISSUE TITLE
Brand and Social Media Icons

### ISSUE THREAD

**Issue by ErikThiart** [twbs/icons#334] opened 2020-06-28 14:39 UTC
The only thing preventing me from using this over fontawesome is the brand icons.

I am assuming legal reasons for why they do not exist?

Example:
Twitter, linkedin, Facebook, Google, Cpanel, Linux, PHP, Youtube (etc ...) you get the point.

**Comment by mdo** [comment] 2020-06-28 16:53
Duplicate of #96.

**Closed by mdo** 2020-06-28 16:53 UTC
Labels: icon-request
