### ISSUE TITLE
Bluesky Icon

### ISSUE THREAD

**Issue by RAMChYLD** [twbs/icons#2087] opened 2024-12-14 08:23 UTC
Bluesky is an upcoming social media platform intended to be a replacement for Twitter/X, except better moderated. Aside from Twitter/X, Meta's Threads could be thought of as it's immediate competitor. The logo for Bluesky is that of a butterfly.

The service is located at https://bsky.app/

I am writing an app that extensively uses bootstrap icons and I require an icon of Bluesky's butterfly to represent Bluesky for the contacts' page. There is also no generic butterfly icon in the set that I can use as a substitute. 

If you could add the icon, I would be grateful, thanks.

**Comment by dennisschuerholz** [comment] 2024-12-14 16:25
Duplicate of #1886

That being said: I also need it :-)

**Closed** 2024-12-15 00:10 UTC
Labels: icon-request
