### ISSUE TITLE
Icon fonts not rendering correctly

### ISSUE THREAD

**Issue by alaurosancsoft** [twbs/icons#588] opened 2020-12-23 16:40 UTC
![bootstrap-icons](https://user-images.githubusercontent.com/3515181/103018352-1c836380-4513-11eb-8052-afb7a7f03136.png)
I noticed when using the chat icons; they mostly appear to be filled.

**Comment by djmagnusa** [comment] 2020-12-23 17:01
I recommend you to try using an icon with .svg (Scalable Vector Graphics) format as it allows every element in SVG files to be animated. I'm pretty sure it will fix your issue.

**Comment by bjsintay** [comment] 2020-12-23 17:02
Mine are doing the same thing. Most things with a box are filled black.

The page that is referenced above in the other user's report/screenshot is the index.html page which I would expect show all icons correctly no matter if SVG is used or not. The screenshot above is exactly how mine looks.

**Comment by mdo** [comment] 2020-12-23 17:04
Duplicate of #545, please search next time.

**Closed by mdo** 2020-12-23 17:04 UTC
Labels: bug
