### ISSUE TITLE
Requesting to add doctor and medical icons

### ISSUE THREAD

**Issue by emranffl** [twbs/icons#1139] opened 2021-12-11 08:36 UTC
Doctor/nurse, hospital building, stethoscope, surgery, etc, related icons are necessary and are missing.  Kindly add them.

**Comment by korki43** [comment] 2022-01-03 01:55
fontawesome `medical` for inspiration
https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=medical&s=solid&m=free

**Comment by mdo** [comment] 2022-01-19 21:59
Duplicate of #850.

**Closed by mdo** 2022-01-19 21:59 UTC
Labels: icon-request
