### ISSUE TITLE
Vertical align looks better as text-top than as text-bottom

### ISSUE THREAD

**Issue by johnaau** [twbs/icons#601] opened 2020-12-25 21:41 UTC
I've noticed when using the Bootstrap Icon web font that the icons don't vertically align well with the surrounding text.

After changing vertical-align from text-bottom to text-top they align much better.

Some examples of icons placed alongside text and in buttons:

![Capture](https://user-images.githubusercontent.com/6590573/103142358-f994c180-4755-11eb-9b1b-c02f9c3ab419.JPG)

**Comment by christianwgd** [comment] 2021-01-04 15:36
That seems to be a general issue. I saw this in a simple paragraph:
`<p style="font-size:2rem;">some text <i class="bi-calendar"></i> some other text</p>`
<img width="406" alt="unaligned" src="https://user-images.githubusercontent.com/9281647/103551349-83593300-4eaa-11eb-91f8-76912991393e.png">
All icons have lower alignment as the text, independent from any vertical alignment for the paragraph.

**Comment by christianwgd** [comment] 2021-01-04 17:52
After testing a lot, i have to admit, that the position seems technically correct. As soon as you add some characters  with descenders, the icon is positioned correct in the middle. I noticed the problem after switching from FontAwesome to Bootstrap Icons and at some point FA seems to have a smarter solution for the icon positioning in text paragraphs.
Text without descenders combined with a bootstrap icon looks really ugly, but at this point i have no idea how to improve that. 

In the following sample the calendar icon is bootstrap and the clock icon is font awesome (there is no different css):
<img width="239" alt="bs_vs_fa_icon" src="https://user-images.githubusercontent.com/9281647/103563936-f0c28f00-4ebd-11eb-9d2b-6c2134488ca5.png">

**Comment by mdo** [comment] 2021-01-04 17:59
FontAwesome uses more specific `vertical-align` values, including custom `vertical-align` and sizing for large (and maybe small?) sized icons. I could see about adding something like this ourselves, too. If anyone wants to experiment with additional values, I'm down to help review and test PRs or even CodePen demos :).

**Comment by mdo** [comment] 2021-01-04 18:00
That said, closing as duplicate of #82.

**Closed by mdo** 2021-01-04 18:00 UTC
Labels: bug
