### ISSUE TITLE
bi-1-circle-fill not showing the number

### ISSUE THREAD

**Issue by georgina1278** [twbs/icons#1463] opened 2022-10-26 08:30 UTC
Hi,

I am using v1.9.1 and I found that the icon "bi-1-circle-fill" is not working as expected.

I used the following html code:
<i class="bi bi-1-circle-fill"></i>

ERROR:
Shows a filled circle without the number 1 inside.

I found following Icon not working when using it by icon-font v1.9.1:

bi-1-circle-fill
Used HTML-Code: <i class="bi bi-1-circle-fill"></i>

ERROR IS:
Only filled circle shows up without number

The CSS-Code shows the following content:

.bi-1-circle-fill::before { 
        content: "\f796"; 
}

Using: 

Windows 10
Chrome v106

Thank you for your help!

**Comment by mdo** [comment] 2022-10-29 17:52
Duplicate of #1385.

**Closed by mdo** 2022-10-29 17:52 UTC
Labels: bug
