### ISSUE TITLE
language icon

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/icons#566] opened 2020-12-20 09:07 UTC
language icon

Examples:
![image](https://user-images.githubusercontent.com/20210961/102709452-a4d9de00-425f-11eb-8602-3eace42207d2.png)
![image](https://user-images.githubusercontent.com/20210961/102709456-aacfbf00-425f-11eb-8687-46d5b929a5bd.png)
![image](https://user-images.githubusercontent.com/20210961/102709458-ae634600-425f-11eb-9013-1fd3d8f6a610.png)

**Comment by mdo** [comment] 2020-12-22 23:32
Duplicate of #168, please search next time.

**Closed by mdo** 2020-12-22 23:32 UTC
Labels: icon-request
