### ISSUE TITLE
Request for Mega Phone icon

### ISSUE THREAD

**Issue by techmeav** [twbs/icons#424] opened 2020-09-05 02:03 UTC
Hi there this is Anirudh. I am requesting for a megaphone icon, silent icon 📢 and loud icon like these emojies 📣.
I hope that BootStrap makes these icons.
Thanks in Advance

**Comment by techmeav** [comment] 2020-09-05 02:11
> Hi there this is Anirudh. I am requesting for a megaphone icon, silent icon 📢 and loud icon like these emojies 📣.
> I hope that BootStrap makes these icons.
> Thanks in Advance

Also I want the icon in line not solid

**Comment by dsentker** [comment] 2020-10-08 14:57
+1

**Comment by ffes** [comment] 2020-11-17 13:22
dup of #357?

**Comment by techmeav** [comment] 2020-11-23 12:23
No

**Comment by mdo** [comment] 2020-12-29 05:14
Duplicate of #357.

**Closed by mdo** 2020-12-29 05:14 UTC
Labels: icon-request
