### ISSUE TITLE
A number of icons font is black color!

### ISSUE THREAD

**Issue by Gh-Moradi** [twbs/icons#587] opened 2020-12-23 16:35 UTC
![Screenshot_2020-12-23 bootstrap-icons](https://user-images.githubusercontent.com/46066206/103018144-f8974080-4559-11eb-9150-ed71235bbcdd.png)

what is the problem?

**Comment by mdo** [comment] 2020-12-23 17:04
Duplicate of #545, please search next time.

**Closed by mdo** 2020-12-23 17:04 UTC
Labels: bug
