### ISSUE TITLE
Ability to change the font path

### ISSUE THREAD

**Issue by ffes** [twbs/icons#760] opened 2021-02-19 08:04 UTC
Right now the location of the font file is hardcoded:
https://github.com/twbs/icons/blob/a744fc530184be03c0c314eed3d4e10b10c9f74c/font/bootstrap-icons.css#L3

In another similar project it is possible to [adjust this path with a SASS variable](https://fontawesome.com/how-to-use/on-the-web/using-with/sass#compile).

It would be really great if bootstrap icons could get a similar setting.

**Comment by mdo** [comment] 2021-02-20 17:48
Duplicate of #563.

**Closed by mdo** 2021-02-20 17:48 UTC
