### ISSUE TITLE
Ban/reject  icon

### ISSUE THREAD

**Issue by jonalxh** [twbs/icons#682] opened 2021-01-12 17:30 UTC
Currently there is an icon called slash-circle but it is very different to main idea of a ban icon.

![image](https://user-images.githubusercontent.com/12530606/104350188-df870d00-54d1-11eb-948f-748e339d5a83.png)

**Comment by mdo** [comment] 2021-01-12 22:50
Duplicate of #681

**Closed by mdo** 2021-01-12 22:50 UTC
Labels: icon-request
