### ISSUE TITLE
New icon for "unlink"

### ISSUE THREAD

**Issue by jnicouleaud** [twbs/icons#1731] opened 2023-06-01 17:02 UTC
Hi,

There are 2 icons to represent linking in the library :
![image](https://github.com/twbs/icons/assets/30346806/30160001-fdc9-4155-b5e8-9695953889c7)

I'm look for an icon that would represent "unlinking", something like this :
![image](https://github.com/twbs/icons/assets/30346806/4f24af62-ab00-448a-b8f3-21a01c571a37)

Is there any existing icon that would be suitable (I couldn't find one...) or are you planning on adding such an icon ?

Thanks,
Julien

**Comment by mdo** [comment] 2023-06-14 21:25
Duplicate of #436.

**Closed by mdo** 2023-06-14 21:25 UTC
