### ISSUE TITLE
Include tags in the icon search

### ISSUE THREAD

**Issue by LarsFlieger** [twbs/icons#222] opened 2020-04-16 13:42 UTC
It's really frustrating if you look for an icon and can't find it with your query and see that exact this query is a tag.

For example an **edit icon**: 

Name is: Pencil square
Tags: edit, write

You won't find it by typing in edit..

**Comment by mdo** [comment] 2020-04-19 21:30
Duplicate of #193.

I know it's frustrating, I haven't had a chance to dive in and figure it out yet. You're obviously welcome to chip in with a PR if you have a solution in mind :).

**Closed by mdo** 2020-04-19 21:30 UTC
