### ISSUE TITLE
Gear Icons is not positioned properly

### ISSUE THREAD

**Issue by azizur** [twbs/icons#242] opened 2020-05-16 16:05 UTC
## [Gear wide connected](https://icons.getbootstrap.com/icons/gear-wide-connected/)
![Screenshot 2020-05-16 at 05 54 52](https://user-images.githubusercontent.com/114551/82124462-10723f00-9797-11ea-8bb0-d4f599b9a787.png)

## [Gear wide](https://icons.getbootstrap.com/icons/gear-wide/)
![Screenshot 2020-05-16 at 17 03 52](https://user-images.githubusercontent.com/114551/82124516-516a5380-9797-11ea-96a9-f81a0ba03a9c.png)

**Comment by mdo** [comment] 2020-05-17 17:39
Duplicate of #163.

**Closed by mdo** 2020-05-17 17:39 UTC
