### ISSUE TITLE
add database icon

### ISSUE THREAD

**Issue by NylePudding** [twbs/icons#1000] opened 2021-09-01 12:36 UTC
An icon for a database/data storage would be nice :)

EDIT: After having a second look through the icons, I noticed once for a server that would do the job, it would be nice to have a server icon with a little cog or something to represent a database though.

**Comment by vanillajonathan** [comment] 2021-10-01 23:01
Icon of relevance:
https://icons.getbootstrap.com/icons/gear/

See #207 for a request for a whole set of database-related icons.

**Comment by mdo** [comment] 2022-10-29 19:34
Duplicate of #207.

**Closed by mdo** 2022-10-29 19:34 UTC
Labels: icon-request
