### ISSUE TITLE
Search fails on hyphen

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#895] opened 2021-05-17 17:32 UTC
When I search for "box-arrow" (hyphen) I get no search results, but when I search for "box arrow" (space) then I do get search results.

**Comment by korki43** [comment] 2022-12-07 22:35
Caused by https://github.com/javve/list.js/issues/699. List.js is unmaintained so this probably won't be fixed there anytime soon. We're currently discussing about switching to an alternative library (#1432).

**Closed** 2023-03-26 15:37 UTC
Labels: bug, docs, help wanted
