### ISSUE TITLE
Icon vertical alignment

### ISSUE THREAD

**Issue by pytchoun** [twbs/icons#721] opened 2021-02-02 22:06 UTC
I used fontawesome before and now with bootstrap icon my icon are set to bottom that need to be a little more up / center
https://i.imgur.com/WiILD5K.png
https://i.imgur.com/LebCrae_d.webp?maxwidth=760&fidelity=grand

**Comment by mdo** [comment] 2021-02-20 18:12
Duplicate of #82, which is coming in v1.4.0 next week.

**Closed by mdo** 2021-02-20 18:12 UTC
Labels: bug
