### ISSUE TITLE
Fonts icons are not accurate - please fix

### ISSUE THREAD

**Issue by muthuweb** [twbs/icons#574] opened 2020-12-22 13:07 UTC
I was waiting for the font icons, finally it's available now with this new version v1.2.1, Thanks for that.
But I just noticed some icons are not accurate by comparing with SVG, I did not mean the quality of icons, I'm talking about the icons variation for example please check **geo-alt-fill** and **geo-alt** both look same in fonts icons.. the same for most of icons too.. 

Please check this screenshot of the fonts icons I see
![image](https://user-images.githubusercontent.com/19426645/102891371-14301780-4484-11eb-8c23-05bbed68e309.png)

This is what we can see the normal/correct icons in SVG
![image](https://user-images.githubusercontent.com/19426645/102891438-32961300-4484-11eb-95ea-bb524ff360e3.png)

You can see same issue everywhere in this screenshot... just check the normal icons and filled icons are look same.
![image](https://user-images.githubusercontent.com/19426645/102891684-a1736c00-4484-11eb-8d0e-d83e9218e1bf.png)

**Solution tips:**
This may happening while converting svg to fonts, I faced the same with gulp-icon, then I tried with http://icomoon.io website to convert myself, then it's almost fine.

**Comment by HGCollier** [comment] 2020-12-22 16:30
This is a duplicate of #545

**Closed** 2020-12-22 17:42 UTC
Labels: bug
