### ISSUE TITLE
Floppy disk for save action.

### ISSUE THREAD

**Issue by urza** [twbs/icons#1777] opened 2023-07-25 18:34 UTC
I don't want "download" icon on "save". I need "save current work" which is represented by floppy disk, not "down arrow". Please add this important and crucial icon.

**Comment by Aworldc** [comment] 2023-07-25 21:30
Yes. please.

**Comment by shaunroselt** [comment] 2023-07-26 09:22
This is a possible duplicate of https://github.com/twbs/icons/issues/1599

**Comment by Aworldc** [comment] 2023-07-27 03:11
> This is a possible duplicate of #1599

Yes, but no one has taken action yet.

**Closed** 2023-07-27 05:25 UTC
Labels: icon-request

**Comment by shaunroselt** [comment] 2023-07-27 06:55
@mdo "closed this as not planned" ???

**Comment by mdo** [comment] 2023-07-27 06:56
As mentioned, it’s a duplicate issue. And GitHub has no mark as dupe option.
