### ISSUE TITLE
I miss the Cut, Copy, Paste, Undo and Redo 

### ISSUE THREAD

**Issue by tonibabieka** [twbs/icons#1157] opened 2022-01-01 17:23 UTC
I miss the cut, copy, paste, undo and redo icons.
It would be nice some data add, remove and edit icons.
Thanks
Tony

**Comment by korki43** [comment] 2022-01-03 01:04
What icons do you expect for cut, copy, paste, undo and redo?

I think these (already existing icons) are recognizable:
- cut: `scissors`
- copy: `clipboard`
- paste: `clipboard-plus`
- undo/redo: some arrow to the left or right

You can search for icons in the documentation (https://icons.getbootstrap.com/). For explicit undo and redo icons see #909.

**Comment by mdo** [comment] 2022-01-20 02:36
Semi-duplicate of #909. Rest is covered by other options as mentioned above.

**Closed by mdo** 2022-01-20 02:36 UTC
Labels: icon-request
