### ISSUE TITLE
Handicap and accessibility icons

### ISSUE THREAD

**Issue by ker0x** [twbs/icons#1801] opened 2023-09-04 07:45 UTC
Hello and thank you for your work.

I would like to submit a new request for handicap and accessibility icons. Something similar to [Tabler's handicap icons](https://tabler-icons.io/)

**Comment by mdo** [comment] 2023-09-12 03:37
We have accessibility icons. Wheelchair dupe of #1537.

**Closed by mdo** 2023-09-12 03:37 UTC
Labels: icon-request
