### ISSUE TITLE
Transport Icons

### ISSUE THREAD

**Issue by adamfitton** [twbs/icons#1074] opened 2021-11-02 18:17 UTC
Request for transport icons:
- Bus
- Train
- Airplane
- Truck
- Car
- Railway
- Road
- Tram
- Bike
- Motorbike
- Helicopter
- Boat

**Comment by vanillajonathan** [comment] 2021-11-04 10:22
- Airship
- Armoured personnel carrier (APC)
- Battle tank
- Drone
- Hot-air balloon 🎈
- Hovercraft
- Hyperloop
- Jetpack 😁
- Space shuttle 🚀
- Subway 🚇

**Comment by mdo** [comment] 2022-02-08 04:48
Duplicate of #886.

**Closed by mdo** 2022-02-08 04:48 UTC
Labels: icon-request
