### ISSUE TITLE
Blurry menu/list icon, sitting on half pixel

### ISSUE THREAD

**Issue by Alexn117** [twbs/icons#1169] opened 2022-01-14 06:18 UTC
The path of the list icon is sitting on half pixels and thus making it blurry. Especially noticeable at the base 16 pixel size. Is this by design for some reason?

I copied the SVG into Figma and tweaked it to sit on whole pixels and the results are much sharper and crisp. Not sure if other icons in the library have this same behavior. Icon tutorials state to snap icon paths to whole pixels and avoid half pixels for the blurriness that is produced. Please see comparison screenshot below.

![Screen Shot 2022-01-14 at 12 44 43 AM](https://user-images.githubusercontent.com/29024614/149459678-89a05c05-4dbc-44bc-99f6-f968f542c571.png)

(original icon in red)
![Screen Shot 2022-01-14 at 12 48 42 AM](https://user-images.githubusercontent.com/29024614/149459712-c1500fe4-33f6-47df-9130-66e0607364e6.png)

**Comment by mdo** [comment] 2022-01-19 22:14
Duplicate of #807.

**Closed by mdo** 2022-01-19 22:14 UTC
Labels: bug

**Comment by Alexn117** [comment] 2022-01-28 01:53
> #807

Thank you for the response. The issue referenced is about this icon being slightly up on its 16px grid to prevent blurriness if you were to fully center it vertically as the OP desired. I agree with this decision, the issue I brought up is different. What I pointed out is that the current icon's paths are actually not sitting on whole pixels, the 3 lines are sitting on half pixels (see red lines of screenshot, they are the current icon from the library). Please test it in Figma, for example, to see. The icon's page also renders the icon blurry at small sizes if you take a closer look under the "[Examples](https://icons.getbootstrap.com/icons/list/)" section.
