### ISSUE TITLE
Icon search to include alternative names

### ISSUE THREAD

**Issue by flipchart** [twbs/icons#214] opened 2020-04-08 09:13 UTC
[Glyphsearch](https://glyphsearch.com) has several search terms associated with each icon to make finding an icon easier. Would be great to have the same here. 

Also, would be great to have Bootstrap icons added to Glyphsearch 😁

**Comment by mdo** [comment] 2020-04-08 17:39
Duplicate of #193.

**Closed by mdo** 2020-04-08 17:39 UTC
