### ISSUE TITLE
Easier way to embed

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#336] opened 2020-06-29 08:40 UTC
The code required for embedding the icons is rather cumbersome compared to how easy it is with Font Awesome.

https://fontawesome.com/icons/bootstrap?style=brands

```html
<i class="fab fa-bootstrap"></i>
```

**Comment by mdo** [comment] 2020-06-29 17:27
Duplicate of #86.

There's also an SVG sprite for super easy inclusion: reference one file and then pull in any icon. Fonts hopefully coming in our next release, v1 stable.

**Closed by mdo** 2020-06-29 17:27 UTC
Labels: bug

**Comment by vanillajonathan** [comment] 2020-06-30 10:17
Even with the SVG sprite it is not as easy.

Compare:
```html
<svg class="bi" width="32" height="32" fill="currentColor">
  <use xlink:href="bootstrap-icons.svg#heart-fill"/>
</svg>
```
vs
```html
<i class="fab fa-bootstrap"></i>
```
