### ISSUE TITLE
Separate icons by categories

### ISSUE THREAD

**Issue by WinterSilence** [twbs/icons#1137] opened 2021-12-10 13:38 UTC
Current "all in" pack already have size ~ 100Kb and will grow up. In most cases you don't need all icons. Yes, I'm can "customize" pack, but it's not so handy.

**I vote to separate icons into categories/sets to optional include in projects.**

Icons already separated by categories in docs:

https://github.com/twbs/icons/blob/b69fe3911e064d1baa772393aa96bb082f420872/docs/content/icons/123.md?plain=1#L4

we need do only few steps to move icons in category sub-directories and generates multiple font/css files

**Comment by WinterSilence** [comment] 2022-02-04 12:45
[solution for similar package `@tabler/icons`](https://github.com/WinterSilence/tabler-icons/blob/b36bc875e181b488b147099782520c6fd2765060/gulpfile.js#L27)

**Comment by WinterSilence** [comment] 2022-03-08 01:46
@mdo it's enhancement - build font tool

**Comment by XhmikosR** [comment] 2022-11-26 07:30
Duplicate of #160.

**Closed by XhmikosR** 2022-11-26 07:30 UTC
Labels: docs
