### ISSUE TITLE
Link & UnLink Icon

### ISSUE THREAD

**Issue by csankarbe** [twbs/icons#1603] opened 2023-03-02 17:41 UTC
We have 2 link icons bi-link and bi-link-45deg. Can you add an Unlink icon that indicates the link is broken?

Font Awesome Reference: https://fontawesome.com/search?q=link&o=r

**Comment by FeuerSturm** [comment] 2023-05-01 17:10
I'd love to have "unlink" icons as well.
Thank you!

**Comment by mdo** [comment] 2023-06-14 21:24
Duplicate of #436.

**Closed by mdo** 2023-06-14 21:25 UTC
Labels: icon-request
